#!/bin/bash
#
### BEGIN INIT INFO
# Provides:          rTail-Server
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Service to Start up stopped services at server startup
# Description:       Deamon Service to Start up stopped services at server startup
### END INIT INFO

USER="vagrant"
PRODUCT_CODE="RTAIL_SERVER"
RTAIL_HOME="/opt/rtail"
RTAIL_IP="10.0.2.15"
RTAIL_WP="8181"
RTAIL_UP="9191"
LOCK_FILE="$RTAIL_HOME/rtail.lck"
CMD_START="DEBUG=rtail:* rtail-server --wh $RTAIL_IP --wp $RTAIL_WP --uh $RTAIL_IP --up $RTAIL_UP"
CMD_STOP="kill -9"
JAVA_HOME="/usr/java/latest"

export JAVA_HOME=$JAVA_HOME

# Status the service
status() {
   PID=`ps axww | grep $RTAIL_WP | grep rtail-server | grep -v grep | awk '{print $1}'`
   ps -fp $PID > /dev/null 2>&1
   PIDVAL=$?
   if [ $PIDVAL -eq 0 ]
      then
         echo "$PRODUCT_CODE server is running ..."
      else
         echo "$PRODUCT_CODE server is stopped."
   fi
   return $PIDVAL
}

# Start the service
start() {
   PID=`ps axww | grep $RTAIL_WP | grep rtail-server | grep -v grep | awk '{print $1}'`
   ps -fp $PID > /dev/null 2>&1
   PIDVAL=$?
   if [ $PIDVAL -eq 0 ]
      then
        echo "$PRODUCT_CODE is running."
      else
        echo -n "Starting $PRODUCT_CODE ... "
        touch $LOCK_FILE
        su - $USER -c "$CMD_START > /dev/null 2>&1 &"
        sleep 5
        PID=`ps axww | grep $RTAIL_WP | grep rtail-server | grep -v grep | awk '{print $1}'`
        ps -fp $PID > /dev/null 2>&1
        PIDVAL=$?
        if [ $PIDVAL -eq 0 ]
          then
            echo "success"
          else
            echo "failure"
        fi
   fi
   return $PIDVAL
}


# Stop the service
stop() {
  PID=`ps axww | grep $RTAIL_WP | grep rtail-server | grep -v grep | awk '{print $1}'`
  ps -fp $PID > /dev/null 2>&1
  PIDVAL=$?
  if [ $PIDVAL -eq 0 ]
      then
         echo -n "Stopping $PRODUCT_CODE ... "
         su - $USER -c "$CMD_STOP $PID > /dev/null 2>&1 &"
         rm -f $LOCK_FILE
         sleep 5
         PID=`ps axww | grep $RTAIL_WP | grep rtail-server | grep -v grep | awk '{print $1}'`
         ps -fp $PID > /dev/null 2>&1
         PIDVAL=$?
         if [ $PIDVAL -eq 0 ]
             then
                echo "failure"
                PIDVAL=2
             else
                echo "success"
                PIDVAL=0
         fi
      else
         echo "$PRODUCT_CODE is not running."
         PIDVAL=0
  fi
  return $PIDVAL
}

### main logic ###
case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
status)
    status
    ;;
restart|reload|condrestart)
    stop
    start
    ;;
*)
   echo $"Usage: $0 {start|stop|restart|reload|status}"
   exit 1
esac
exit $?